### ISSUE TITLE
[Enhancement] Better Scene management

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [SPC-Some-Polish-Coders/PopHead#130]
Consider using Swoosh for SFML. It has scene objects (Activities) and come bundled with screen transition effects system out of the box.

https://github.com/TheMaverickProgrammer/Swoosh

**Comment by TheMaverickProgrammer** [comment]
what do you think

**Comment by TheMaverickProgrammer** [comment]
you want to use this it is very mature library and header-only

**Comment by Czapa10** [comment]
We considered deeply using you libary but we're not going to use it. Sorry dude.

**Comment by TheMaverickProgrammer** [comment]
Thanks for your consideration. Why would you not want to? Feedback helps me improve it where it fails.

**Comment by Czapa10** [comment]
I think your libary is nice but we just don't need it. Your libary has mostly scene management and some special graphics effects. And we in PopHead have our own scene managment which is designed for exactly what we need in our game and we'll also have our own materials system and speciall graphics efects in our Renderer.
Your libary is nice but one thing is quite silly to me.
https://github.com/TheMaverickProgrammer/Swoosh#less-typing
Yeah less typing! But also less readable. I really don't know why did you put "Less Typing" feature in your libary dude.

**Comment by TheMaverickProgrammer** [comment]
If you can't read this 

```cpp
using segue  = segue<PixelateFade, sec<2>>;
using transition = segue::to<DramaticIntroScene>;

getController().push<transition>();
```

then there's nothing I can do about that - this library simply won't help you
