### ISSUE TITLE
Make the slower zombie

### ISSUE THREAD

**Issue by Czapa10** [SPC-Some-Polish-Coders/PopHead#317]
The slower zombie should be more less 3 times slower the normal zombie.
In gameplay we will more often see slower zombie but there will be a lot of them.
Slower zombie will have another texture which is already made by SiwyKleszcz. And it's on #art discord channel.
Player has to shoot 3 times from pistol to kill the slower zombie.

Implementation detail:
For now I think you can just make SlowZombie class which inherits from Enemy class. However the decision is yours.

**Comment by izhuravlev** [comment]
Hey @Czapa10,
I am a 3rd-year student of Bachelors of Software Development Program, and I am interested in Game Development. I think that I can work on this issue. Can I contribute to your project? 
Will be happy to hear any recommendations from you! :)

**Comment by Czapa10** [comment]
Hi! @izhuravlev 
Currently @bobsito is working on this issue. But you could do another task. Join our Discord server and write to me. I will give you the access to our git kraken glo task board.
