### ISSUE TITLE
Graphics bug (zombie on top of a dead body)

### ISSUE THREAD

**Issue by PiotrGardocki** [SPC-Some-Polish-Coders/PopHead#448]
![image](https://app.gitkraken.com/api/glo/boards/5caa5323c6c3bd00126a0348/attachments/5ea217da6cb04e001129af08)

**Comment by Czapa10** [comment]
The problem is that zombie and dead body have the same z value.
That's an easy fix but I'm not gonna bother because the dead body is gonna be deleted from the game really soon. (as well as car)
