### ISSUE TITLE
Compiler Errors

### ISSUE THREAD

**Issue by meissner61** [SPC-Some-Polish-Coders/PopHead#454]
getting quite a few compiler errors on VS2022, most of them alluding to 

left of .pos must have class/struct/union any info would be appreciated.

i posted the errors and warnings here
https://pastebin.com/uPYr208j

**Comment by Czapa10** [comment]
I'm sorry you couldn't compile it. We were working on PopHead on VS2019 so the code should compile on VS2019. Unfortunately VS2022 is not backwards compatible with VS2019 in terms of compiling C++ code. We abandoned the project a long time ago so we're not going to fix those compile errors.
